// Copyright (c) Curt Hagenlocher. All rights reserved.
// Licensed under the Apache License, Version 2.0. See LICENSE in the project root for license information.

using Apache.Arrow;
using Apache.Arrow.Types;

namespace EngineeredWood.Lance.Table.Tests;

/// <summary>
/// Cross-validation tests against pylance-produced Lance datasets.
/// Fixtures live under <c>TestData/</c> and are generated by
/// <c>generate_test_data.py</c>.
/// </summary>
public class LanceTableReadTests
{
    [Fact]
    public async Task SimpleDataset_OpenReportsSchemaAndRowCount()
    {
        await using var table = await LanceTable.OpenAsync(TestDataPath.Resolve("simple_v21"));

        Assert.Equal(10L, table.NumberOfRows);
        Assert.Equal(1, table.NumberOfFragments);
        Assert.Equal(2, table.Schema.FieldsList.Count);
        Assert.Equal("id", table.Schema.FieldsList[0].Name);
        Assert.IsType<Int32Type>(table.Schema.FieldsList[0].DataType);
        Assert.Equal("name", table.Schema.FieldsList[1].Name);
        Assert.IsType<StringType>(table.Schema.FieldsList[1].DataType);
    }

    [Fact]
    public async Task SimpleDataset_ReadYieldsAllRows()
    {
        await using var table = await LanceTable.OpenAsync(TestDataPath.Resolve("simple_v21"));

        var batches = new List<RecordBatch>();
        await foreach (var batch in table.ReadAsync())
            batches.Add(batch);

        Assert.Single(batches);
        var only = batches[0];
        Assert.Equal(10, only.Length);

        var ids = (Int32Array)only.Column(0);
        var names = (StringArray)only.Column(1);
        for (int i = 0; i < 10; i++)
        {
            Assert.Equal(i, ids.GetValue(i));
            Assert.Equal($"item-{i}", names.GetString(i));
        }
    }

    [Fact]
    public async Task ThreeFragments_AppendOrderPreserved()
    {
        // Generator: 3 appends of [0..5), [5..10), [10..15) in that order.
        await using var table = await LanceTable.OpenAsync(
            TestDataPath.Resolve("three_fragments_v21"));

        Assert.Equal(15L, table.NumberOfRows);
        Assert.Equal(3, table.NumberOfFragments);

        var batches = new List<RecordBatch>();
        await foreach (var batch in table.ReadAsync())
            batches.Add(batch);

        Assert.Equal(3, batches.Count);
        Assert.Equal(new[] { 5, 5, 5 }, batches.Select(b => b.Length));

        int expected = 0;
        foreach (var batch in batches)
        {
            var x = (Int32Array)batch.Column(0);
            for (int i = 0; i < x.Length; i++)
                Assert.Equal(expected++, x.GetValue(i));
        }
    }

    [Fact]
    public async Task MultiVersion_ReadsLatestSnapshotByDefault()
    {
        // Generator: 3 versions accumulating ["v0a", "v0b"] → ["v1c"] → ["v2d", "v2e"]
        // (each "append" adds a new fragment). Latest manifest sees all 3.
        await using var table = await LanceTable.OpenAsync(
            TestDataPath.Resolve("multi_version_v21"));

        // Version is the latest; pylance starts at version 1, so 3 commits → version 3.
        Assert.True(table.Version >= 3, $"Expected at least 3 versions, got {table.Version}.");
        Assert.Equal(5L, table.NumberOfRows);
        Assert.Equal(3, table.NumberOfFragments);

        var allValues = new List<string>();
        await foreach (var batch in table.ReadAsync())
        {
            var v = (StringArray)batch.Column(0);
            for (int i = 0; i < v.Length; i++) allValues.Add(v.GetString(i));
        }
        Assert.Equal(new[] { "v0a", "v0b", "v1c", "v2d", "v2e" }, allValues);
    }

    [Fact]
    public async Task SimpleDataset_OpenViaFileSystemReusesIt()
    {
        // Open via caller-provided ITableFileSystem (e.g., for Azure / S3
        // backends that provide their own).
        var fs = new EngineeredWood.IO.Local.LocalTableFileSystem(
            TestDataPath.Resolve("simple_v21"));
        await using var table = await LanceTable.OpenAsync(fs);
        Assert.Equal(10L, table.NumberOfRows);
    }

    // --- Projection + filter ---

    [Fact]
    public async Task Projection_ReadsOnlyRequestedColumns()
    {
        await using var table = await LanceTable.OpenAsync(TestDataPath.Resolve("simple_v21"));

        var batches = new List<RecordBatch>();
        await foreach (var b in table.ReadAsync(columns: new[] { "name" }))
            batches.Add(b);

        Assert.Single(batches);
        var batch = batches[0];
        Assert.Equal(1, batch.ColumnCount);
        Assert.Equal("name", batch.Schema.FieldsList[0].Name);
        Assert.Equal(10, batch.Length);

        var names = (StringArray)batch.Column(0);
        for (int i = 0; i < 10; i++)
            Assert.Equal($"item-{i}", names.GetString(i));
    }

    [Fact]
    public async Task Projection_ReordersColumns()
    {
        // Schema order is [id, name]; ask for [name, id].
        await using var table = await LanceTable.OpenAsync(TestDataPath.Resolve("simple_v21"));
        var batches = new List<RecordBatch>();
        await foreach (var b in table.ReadAsync(columns: new[] { "name", "id" }))
            batches.Add(b);
        var batch = batches[0];
        Assert.Equal("name", batch.Schema.FieldsList[0].Name);
        Assert.Equal("id", batch.Schema.FieldsList[1].Name);
        Assert.IsType<StringArray>(batch.Column(0));
        Assert.IsType<Int32Array>(batch.Column(1));
    }

    [Fact]
    public async Task Projection_UnknownColumn_Throws()
    {
        await using var table = await LanceTable.OpenAsync(TestDataPath.Resolve("simple_v21"));
        var ex = await Assert.ThrowsAsync<ArgumentException>(async () =>
        {
            await foreach (var _ in table.ReadAsync(columns: new[] { "nope" })) { }
        });
        Assert.Contains("'nope'", ex.Message);
        Assert.Contains("Available", ex.Message);
    }

    [Fact]
    public async Task Projection_DuplicateColumn_Throws()
    {
        await using var table = await LanceTable.OpenAsync(TestDataPath.Resolve("simple_v21"));
        var ex = await Assert.ThrowsAsync<ArgumentException>(async () =>
        {
            await foreach (var _ in table.ReadAsync(columns: new[] { "id", "id" })) { }
        });
        Assert.Contains("more than once", ex.Message);
    }

    [Fact]
    public async Task Filter_ComparisonKeepsMatchingRowsOnly()
    {
        // simple_v21 ids = 0..9, want id >= 5.
        await using var table = await LanceTable.OpenAsync(TestDataPath.Resolve("simple_v21"));
        var pred = EngineeredWood.Expressions.Expressions.GreaterThanOrEqual(
            "id", EngineeredWood.Expressions.LiteralValue.Of(5));

        var rows = new List<int>();
        await foreach (var b in table.ReadAsync(columns: null, filter: pred))
        {
            var ids = (Int32Array)b.Column(0);
            for (int i = 0; i < ids.Length; i++) rows.Add(ids.GetValue(i)!.Value);
        }
        Assert.Equal(new[] { 5, 6, 7, 8, 9 }, rows);
    }

    [Fact]
    public async Task Filter_AppliesAcrossFragments()
    {
        // three_fragments_v21 has x = 0..14 across 3 fragments. Filter x % 2 = 0.
        // We only have ==, not modulo, so use IN.
        await using var table = await LanceTable.OpenAsync(
            TestDataPath.Resolve("three_fragments_v21"));
        var pred = new EngineeredWood.Expressions.SetPredicate(
            new EngineeredWood.Expressions.UnboundReference("x"),
            new[]
            {
                EngineeredWood.Expressions.LiteralValue.Of(0),
                EngineeredWood.Expressions.LiteralValue.Of(2),
                EngineeredWood.Expressions.LiteralValue.Of(4),
                EngineeredWood.Expressions.LiteralValue.Of(6),
                EngineeredWood.Expressions.LiteralValue.Of(8),
                EngineeredWood.Expressions.LiteralValue.Of(10),
                EngineeredWood.Expressions.LiteralValue.Of(12),
                EngineeredWood.Expressions.LiteralValue.Of(14),
            },
            EngineeredWood.Expressions.SetOperator.In);

        var got = new List<int>();
        await foreach (var b in table.ReadAsync(columns: null, filter: pred))
        {
            var x = (Int32Array)b.Column(0);
            for (int i = 0; i < x.Length; i++) got.Add(x.GetValue(i)!.Value);
        }
        Assert.Equal(new[] { 0, 2, 4, 6, 8, 10, 12, 14 }, got);
    }

    [Fact]
    public async Task Filter_CombinesWithDeletionMask()
    {
        // deletes_sparse_v21 has 100 rows with ids {5, 17, 42} deleted.
        // Filter id < 20 → kept ids = {0..19} \ {5, 17} = 18 rows.
        await using var table = await LanceTable.OpenAsync(
            TestDataPath.Resolve("deletes_sparse_v21"));
        var pred = EngineeredWood.Expressions.Expressions.LessThan(
            "id", EngineeredWood.Expressions.LiteralValue.Of(20));

        var got = new List<int>();
        await foreach (var b in table.ReadAsync(columns: null, filter: pred))
        {
            var ids = (Int32Array)b.Column(0);
            for (int i = 0; i < ids.Length; i++) got.Add(ids.GetValue(i)!.Value);
        }
        var expected = Enumerable.Range(0, 20).Except(new[] { 5, 17 }).ToArray();
        Assert.Equal(expected, got);
    }

    [Fact]
    public async Task Projection_AndFilter_Combined()
    {
        await using var table = await LanceTable.OpenAsync(TestDataPath.Resolve("simple_v21"));
        var pred = EngineeredWood.Expressions.Expressions.GreaterThanOrEqual(
            "id", EngineeredWood.Expressions.LiteralValue.Of(7));

        var batches = new List<RecordBatch>();
        await foreach (var b in table.ReadAsync(columns: new[] { "name" }, filter: pred))
            batches.Add(b);
        Assert.Single(batches);

        var batch = batches[0];
        Assert.Equal(1, batch.ColumnCount);
        Assert.Equal("name", batch.Schema.FieldsList[0].Name);
        Assert.Equal(3, batch.Length);
        var names = (StringArray)batch.Column(0);
        Assert.Equal(new[] { "item-7", "item-8", "item-9" },
            Enumerable.Range(0, 3).Select(i => names.GetString(i)).ToArray());
    }

    // --- Time travel ---

    [Fact]
    public async Task TimeTravel_OpensSpecificVersion_RowsMatchSnapshot()
    {
        // multi_version_v21 was created by 3 commits:
        //   v1: ["v0a", "v0b"]              (2 rows)
        //   v2: + ["v1c"]                   (3 rows total)
        //   v3: + ["v2d", "v2e"]            (5 rows total)
        string path = TestDataPath.Resolve("multi_version_v21");

        await using (var t1 = await LanceTable.OpenAsync(path, version: 1))
        {
            Assert.Equal(1UL, t1.Version);
            Assert.Equal(2L, t1.NumberOfRows);
            var rows = await CollectStringsAsync(t1);
            Assert.Equal(new[] { "v0a", "v0b" }, rows);
        }

        await using (var t2 = await LanceTable.OpenAsync(path, version: 2))
        {
            Assert.Equal(2UL, t2.Version);
            Assert.Equal(3L, t2.NumberOfRows);
            var rows = await CollectStringsAsync(t2);
            Assert.Equal(new[] { "v0a", "v0b", "v1c" }, rows);
        }

        await using (var t3 = await LanceTable.OpenAsync(path, version: 3))
        {
            Assert.Equal(3UL, t3.Version);
            Assert.Equal(5L, t3.NumberOfRows);
            var rows = await CollectStringsAsync(t3);
            Assert.Equal(new[] { "v0a", "v0b", "v1c", "v2d", "v2e" }, rows);
        }
    }

    [Fact]
    public async Task TimeTravel_UnknownVersion_ThrowsWithAvailableList()
    {
        string path = TestDataPath.Resolve("multi_version_v21");
        var ex = await Assert.ThrowsAsync<LanceTableFormatException>(async () =>
            await LanceTable.OpenAsync(path, version: 999));
        Assert.Contains("999", ex.Message);
        Assert.Contains("Available versions", ex.Message);
    }

    [Fact]
    public async Task TimeTravel_VersionZeroRejected()
    {
        string path = TestDataPath.Resolve("multi_version_v21");
        await Assert.ThrowsAsync<ArgumentOutOfRangeException>(async () =>
            await LanceTable.OpenAsync(path, version: 0));
    }

    [Fact]
    public async Task ListVersions_ReturnsAscendingVersionNumbers()
    {
        string path = TestDataPath.Resolve("multi_version_v21");
        var versions = await LanceTable.ListVersionsAsync(path);
        Assert.Equal(new ulong[] { 1, 2, 3 }, versions);
    }

    private static async Task<string[]> CollectStringsAsync(LanceTable table)
    {
        var values = new List<string>();
        await foreach (var batch in table.ReadAsync())
        {
            var col = (StringArray)batch.Column(0);
            for (int i = 0; i < col.Length; i++) values.Add(col.GetString(i));
        }
        return values.ToArray();
    }

    // --- Deletion files ---

    [Fact]
    public async Task DeletesSparse_ArrowEncoding_RemovesDeletedRows()
    {
        // Generator: 100 rows, deleted ids = {5, 17, 42}. Pylance picks
        // ARROW_ARRAY encoding for this sparse case (.arrow file).
        await using var table = await LanceTable.OpenAsync(
            TestDataPath.Resolve("deletes_sparse_v21"));

        Assert.Equal(97L, table.NumberOfRows); // 100 - 3 deleted

        var batches = new List<RecordBatch>();
        await foreach (var b in table.ReadAsync()) batches.Add(b);
        Assert.Single(batches);
        var batch = batches[0];
        Assert.Equal(97, batch.Length);

        var ids = (Int32Array)batch.Column(0);
        var names = (StringArray)batch.Column(1);
        var deleted = new HashSet<int> { 5, 17, 42 };
        int row = 0;
        for (int i = 0; i < 100; i++)
        {
            if (deleted.Contains(i)) continue;
            Assert.Equal(i, ids.GetValue(row));
            Assert.Equal($"r{i}", names.GetString(row));
            row++;
        }
    }

    [Fact]
    public async Task DeletesDense_BitmapEncoding_RemovesDeletedRows()
    {
        // Generator: 10000 rows, every-other deleted (5000 of 10000).
        // Pylance picks the BITMAP encoding (.bin Roaring file) at this
        // density.
        await using var table = await LanceTable.OpenAsync(
            TestDataPath.Resolve("deletes_dense_v21"));

        Assert.Equal(5000L, table.NumberOfRows);

        var batches = new List<RecordBatch>();
        await foreach (var b in table.ReadAsync()) batches.Add(b);
        Assert.Single(batches);
        var batch = batches[0];
        Assert.Equal(5000, batch.Length);

        // Every surviving row id should be odd.
        var ids = (Int32Array)batch.Column(0);
        for (int i = 0; i < 5000; i++)
            Assert.Equal(2 * i + 1, ids.GetValue(i));
    }
}
