using System.Collections;
using EngineeredWood.IO.Local;
using EngineeredWood.Parquet;
using EngineeredWood.Parquet.BloomFilter;

namespace EngineeredWood.Tests.Parquet;

public class BloomFilterTests
{
    [Fact]
    public void SplitBlockBloomFilter_RawXxHashBin_FindsInsertedValues()
    {
        // bloom_filter.xxhash.bin was generated by parquet-mr with strings:
        // "hello", "parquet", "bloom", "filter"
        var raw = File.ReadAllBytes(TestData.GetPath("bloom_filter.xxhash.bin"));
        var filter = BloomFilterReader.Parse(raw);

        // These values were inserted — should all return true.
        Assert.True(filter.MightContain("hello"u8));
        Assert.True(filter.MightContain("parquet"u8));
        Assert.True(filter.MightContain("bloom"u8));
        Assert.True(filter.MightContain("filter"u8));

        // These values were NOT inserted — should almost certainly return false
        // (false positives are theoretically possible but extremely unlikely with only 4 entries
        // in a 1024-byte filter).
        Assert.False(filter.MightContain("not-in-filter"u8));
        Assert.False(filter.MightContain("definitely-absent"u8));
        Assert.False(filter.MightContain(""u8));
        Assert.False(filter.MightContain("HELLO"u8)); // case-sensitive
    }

    [Fact]
    public async Task GetCandidateRowGroups_BloomEncodingStats_DetectsAbsentValues()
    {
        // data_index_bloom_encoding_stats.parquet has a String column (BYTE_ARRAY)
        // with a bloom filter. Contains values like "Hello" and "today".
        await using var file = new LocalRandomAccessFile(
            TestData.GetPath("data_index_bloom_encoding_stats.parquet"));
        await using var reader = new ParquetFileReader(file, ownsFile: false);

        var metadata = await reader.ReadMetadataAsync();
        var schema = await reader.GetSchemaAsync();

        // Verify bloom filter metadata was parsed.
        var colMeta = metadata.RowGroups[0].Columns[0].MetaData;
        Assert.NotNull(colMeta);
        Assert.NotNull(colMeta.BloomFilterOffset);
        Assert.True(colMeta.BloomFilterOffset > 0);

        // Query with a value that almost certainly is NOT in the data.
        var absent = await reader.GetCandidateRowGroupsAsync("String", "zzz_definitely_not_present");
        // With only 14 rows and a properly sized filter, the absent value should be rejected.
        Assert.False(absent[0]);
    }

    [Fact]
    public async Task GetCandidateRowGroups_BloomEncodingWithLength_HasLengthField()
    {
        // data_index_bloom_encoding_with_length.parquet is identical to the stats variant
        // but has bloom_filter_length populated.
        await using var file = new LocalRandomAccessFile(
            TestData.GetPath("data_index_bloom_encoding_with_length.parquet"));
        await using var reader = new ParquetFileReader(file, ownsFile: false);

        var metadata = await reader.ReadMetadataAsync();
        var colMeta = metadata.RowGroups[0].Columns[0].MetaData;
        Assert.NotNull(colMeta);
        Assert.NotNull(colMeta.BloomFilterOffset);
        Assert.NotNull(colMeta.BloomFilterLength);
        Assert.True(colMeta.BloomFilterLength > 0);

        // Same absent-value test.
        var absent = await reader.GetCandidateRowGroupsAsync("String", "zzz_definitely_not_present");
        Assert.False(absent[0]);
    }

    [Fact]
    public async Task GetCandidateRowGroups_MultipleValues_OrSemantics()
    {
        await using var file = new LocalRandomAccessFile(
            TestData.GetPath("data_index_bloom_encoding_stats.parquet"));
        await using var reader = new ParquetFileReader(file, ownsFile: false);

        // One absent, one possibly present — row group should be a candidate (OR semantics).
        var mixed = await reader.GetCandidateRowGroupsAsync(
            "String", new object[] { "Hello", "zzz_definitely_not_present" });
        // "Hello" is in the data, so the row group should be marked as candidate.
        Assert.True(mixed[0]);
    }

    [Fact]
    public async Task GetCandidateRowGroups_NoBloomFilter_ReturnsAllTrue()
    {
        // alltypes_plain.parquet has no bloom filters.
        await using var file = new LocalRandomAccessFile(
            TestData.GetPath("alltypes_plain.parquet"));
        await using var reader = new ParquetFileReader(file, ownsFile: false);

        var result = await reader.GetCandidateRowGroupsAsync("id", 42);

        // No bloom filter → all row groups conservatively marked as candidates.
        Assert.True(result[0]);
    }

    [Fact]
    public void SplitBlockBloomFilterBuilder_RoundTrip()
    {
        // Build a filter, serialize it, parse it back, and verify probing works.
        int numBytes = SplitBlockBloomFilterBuilder.OptimalNumBytes(100, 0.05, 1024 * 1024);
        var builder = new SplitBlockBloomFilterBuilder(numBytes);

        var values = new[] { "hello", "world", "bloom", "filter" };
        foreach (var v in values)
            builder.Add(System.Text.Encoding.UTF8.GetBytes(v));

        var serialized = BloomFilterSerializer.Serialize(builder.ToArray());
        var filter = BloomFilterReader.Parse(serialized);

        foreach (var v in values)
            Assert.True(filter.MightContain(System.Text.Encoding.UTF8.GetBytes(v)),
                $"Expected '{v}' to be found in round-tripped filter.");

        Assert.False(filter.MightContain("absent"u8));
        Assert.False(filter.MightContain("not-inserted"u8));
    }

    [Fact]
    public async Task RoundTrip_WriteAndReadBloomFilters()
    {
        var path = Path.GetTempFileName();
        try
        {
            // Write a Parquet file with bloom filters on the "name" column.
            var schema = new Apache.Arrow.Schema.Builder()
                .Field(new Apache.Arrow.Field("id", Apache.Arrow.Types.Int32Type.Default, false))
                .Field(new Apache.Arrow.Field("name", Apache.Arrow.Types.StringType.Default, false))
                .Build();

            var ids = new Apache.Arrow.Int32Array.Builder();
            var names = new Apache.Arrow.StringArray.Builder();
            for (int i = 0; i < 100; i++)
            {
                ids.Append(i);
                names.Append($"name_{i}");
            }

            var batch = new Apache.Arrow.RecordBatch(schema, new Apache.Arrow.IArrowArray[]
            {
                ids.Build(), names.Build()
            }, 100);

            var writeOptions = new ParquetWriteOptions
            {
                BloomFilterColumns = new HashSet<string> { "name" },
                BloomFilterFpp = 0.01,
            };

            await using (var file = new EngineeredWood.IO.Local.LocalSequentialFile(path))
            await using (var writer = new ParquetFileWriter(file, ownsFile: false, writeOptions))
            {
                await writer.WriteRowGroupAsync(batch);
            }

            // Read back and verify bloom filter works.
            await using var readFile = new LocalRandomAccessFile(path);
            await using var reader = new ParquetFileReader(readFile, ownsFile: false);

            var metadata = await reader.ReadMetadataAsync();
            Assert.NotNull(metadata.RowGroups[0].Columns[1].MetaData?.BloomFilterOffset);
            Assert.NotNull(metadata.RowGroups[0].Columns[1].MetaData?.BloomFilterLength);

            // Present value should be found.
            var present = await reader.GetCandidateRowGroupsAsync("name", "name_0");
            Assert.True(present[0], "Should find present value 'name_0'.");

            // Absent value should be rejected.
            var absent = await reader.GetCandidateRowGroupsAsync("name", "zzz_absent");
            Assert.False(absent[0], "Should reject absent value.");

            // Column without bloom filter should be conservatively included.
            var noFilter = await reader.GetCandidateRowGroupsAsync("id", 42);
            Assert.True(noFilter[0], "Column without bloom filter should be included.");
        }
        finally
        {
            File.Delete(path);
        }
    }

    [Fact]
    public async Task GetCandidateRowGroups_InvalidColumn_Throws()
    {
        await using var file = new LocalRandomAccessFile(
            TestData.GetPath("data_index_bloom_encoding_stats.parquet"));
        await using var reader = new ParquetFileReader(file, ownsFile: false);

        await Assert.ThrowsAsync<ArgumentException>(
            () => reader.GetCandidateRowGroupsAsync("NonExistentColumn", "value").AsTask());
    }

    [Fact]
    public async Task GetCandidateRowGroups_TypeMismatch_Throws()
    {
        await using var file = new LocalRandomAccessFile(
            TestData.GetPath("data_index_bloom_encoding_stats.parquet"));
        await using var reader = new ParquetFileReader(file, ownsFile: false);

        // String column is BYTE_ARRAY — passing an int should throw.
        await Assert.ThrowsAsync<ArgumentException>(
            () => reader.GetCandidateRowGroupsAsync("String", 42).AsTask());
    }
}
